variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages: 

  - build
  - test
  - deploy

build:

    tags:
        - astra

    script:
        - echo "building..."
        - echo  mkdir build
        - echo  cd ./build
        - echo  qmake ..
        - echo  make
        - echo "building is complete"

test:

    tags:
        - astra

    script:
        - echo "testing..."
        - echo "testing is complete"
  
  
deploy:

    tags:
        - astra
    
    script:
        - echo "deploying..."
        - echo "deploying is complete"
    
