variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages: 

  - build
  - test
  - deploy

build:

    tags:
        - astra

    script:
        - echo $(pwd)
        - mkdir build
        - cd ./build
        - qmake ..
        - make


test:

    tags:
        - astra

    script:
        - echo "test ok"
  
  
deploy:

    tags:
        - astra
    
    script:
        - echo "deploy ok"
    
