variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages: 

  - build
  - test
  - deploy

build:

    tags:
        - astra_plotter

    script:
        - echo "building..."
        - mkdir build
        - cd ./build
        - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake ..
        - make -j10
        - echo "building is complete"
        
    artifacts:
        paths:
            - build

test:

    tags:
        - astra_plotter

    script:
        - echo "testing..."
        - echo "testing is complete"
  
  
deploy:

    tags:
        - astra_plotter
    
    script:
        - echo "deploying..."
        - echo "deploying is complete"
    
